# Generated by Django 3.1.4 on 2023-10-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('info', models.TextField()),
                ('rules', models.TextField(blank=True, null=True)),
                ('prizes', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('isactive', models.BooleanField(default='false')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-isactive',),
            },
        ),
    ]
