# Generated by Django 3.1.4 on 2023-10-15 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_submissionmodel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submissionmodel',
            unique_together={('project', 'email')},
        ),
    ]
